# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/18/8.yaml

extra-deps: [repa-3.4.1.4, accelerate-1.3.0.0, accelerate-io-vector-0.1.0.0, accelerate-llvm-native-1.3.0.0, accelerate-llvm-1.3.0.0]

packages:
- .

